battleship/config/routes.rb
Rails.application.routes.draw do

  root 'games#index'

  get 'play_game' => 'games#play_game'

  post 'take_shot' => 'shots#take_shot'

  resources :players, only: [:create]

  resources :games, only: [:index, :create]

end

battleship/app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  has_many :ships
  has_many :shots

end

battleship/app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  has_many :boards

 def start_game
  boards = players.map do |player|
    player.boards.create game_id: self.id
  end
  boards.each do |board|
    5.times do 
      Ship.create_random(board: board)
    end
  end
 end



end

battleship/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
  has_many :boards

end

battleship/app/models/ship.rb
class Ship < ActiveRecord::Base
  belongs_to :board

  validates :start_row_index, :numericality => { :less_than => 9 }
  validates :start_col_index, :numericality => { :less_than => 9 }
  validates :end_row_index, :numericality => { :less_than => 9 }
  validates :end_col_index, :numericality => { :less_than => 9 }


  def self.create_random(board:)
    starting_point = ["row", "column"].sample
    length = rand(2..5)
    start_row_index = rand(0..9)
    start_col_index = rand(0..9)
    end_row_index, end_col_index = if starting_point == "row"
      [start_row_index + length, start_col_index]
    else
      [start_row_index, start_col_index + length]
    end
    ship = self.create(board: board, start_row_index: start_row_index, 
      end_row_index: end_row_index,
      start_col_index: start_col_index,
      end_col_index: end_col_index
      )

    unless ship.valid?
      self.create_random(board: board)
    end
  end

  def coordinates
    row_indices = (self.start_row_index..self.end_row_index).to_a
    col_indices = (self.start_col_index..self.end_col_index).to_a
    row_indices.product(col_indices)
  end

end

battleship/app/models/shot.rb
class Shot < ActiveRecord::Base
  belongs_to :board

  def generate_coordinates
    self.row_index = rand(0..9)
    self.col_index = rand(0..9)
  end

end

battleship/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

battleship/app/controllers/games_controller.rb
require 'active_gameboard'

class GamesController < ApplicationController
  helper_method :game_loaded?, :need_more_players?
  
  def index
    if session[:player]
      @player = Player.find(session[:player])
    else
      @player = Player.new
    end
  end

  def create
    @game = Game.new
    if @game.save
      Player.all.map {|player| player.update_attributes(game: @game)}
      @game.start_game
      redirect_to play_game_path
    else
      redirect_to root_path
    end
  end


  def play_game
    @game = Game.find(1)
    @player = Player.find(session[:player])
    @board = @player.boards.last
    @active_gameboard = ActiveGameboard.new(ships: @board.ships).call
  end

  def update_game
  end


  def game_loaded?
    Game.exists?(1)
  end

  def need_more_players?
    Player.all.count < 2
  end
end

battleship/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  helper_method :need_more_players?

  def create
    @player = Player.new
    if @player.save
      session[:player] = @player.id
      redirect_to root_path
    else
      redirect_to root_path
    end
  end


end

battleship/app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  respond_to :js, :json, :html

  def take_shot
    @shot = Shot.new
    if @shot.save
      @shot.generate_coordinates
      render :json => @shot
    end
  end



end

battleship/app/helpers/application_helper.rb
module ApplicationHelper
end

battleship/app/views/games/index.html.erb
<div class="login">
  <% if need_more_players? %>  
    <%= render :partial => '/players/create_players' %>
  <% else %>
    <div class="game_button">
      <p>Welcome Player <%="#{@player.id}"%>!</p>
      <%= form_tag games_path do %>
        <%= submit_tag "Load Game!"%>
      <% end %>
  <%end %>
    </div>
</div>

battleship/app/views/games/play_game.html.erb
<% 
  @page_css = "game"
  @js_manifest = "backbone/battleship" 
%>
<button class="fire-missile" rel="fire-missile">Fire Missile!</button>

<div class="main"></div>

<% content_for :javascript do %>
  <%= javascript_tag do %>
    jQuery(function($){
      Battleship.start({
       coordinates: <%= raw @active_gameboard.to_json %>
      });
    });
  <% end %>
<% end %>

battleship/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Battleship</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="welcome"><h1>WELCOME TO BATTLESHIP</h1></div>
<%= yield %>

</body>
</html>

battleship/app/views/players/_create_players.html.erb
<div class="create_players">
  <% if session[:player] %>
  <p>Waiting for one more player to sign in!</p>
<% else %>
  <%= form_for(@player) do |f| %>
    <%= f.submit %>
  <% end %>
<% end %>
</div>